apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: ride-platform
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: api-gateway
          image: <ECR_REPO>/api-gateway:latest
          ports:
            - containerPort: 8080
          env:
            - name: LOCATION_SERVICE_URL
              value: "http://location-service"
            - name: MATCHING_SERVICE_URL
              value: "http://trip-matching-service"
            - name: SURGE_SERVICE_URL
              value: "http://surge-pricing-service"
            - name: PAYMENT_SERVICE_URL
              value: "http://payment-service"
            - name: USER_SERVICE_URL
              value: "http://user-service"
            - name: ADMIN_SERVICE_URL
              value: "http://admin-service"
            - name: REDIS_ADDR
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: addr
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: secret
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://jaeger:4318"
          resources:
            requests:
              cpu: "250m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: ride-platform
spec:
  selector:
    app: api-gateway
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer   # AWS NLB — gets a public DNS name
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-gateway-hpa
  namespace: ride-platform
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-gateway
  minReplicas: 3
  maxReplicas: 15
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
